import { WorkspaceWithDetails } from "@/types/database";

export const initialWorkspaces: WorkspaceWithDetails[] = [
  {
    id: "ws-1",
    user_id: "demo-user",
    name: "Main Projects",
    description: "Primary work and personal organization workspace",
    created_at: "2026-09-01T08:00:00.000Z",
    updated_at: "2026-09-20T10:00:00.000Z",
    categories: [
      {
        id: "cat-1",
        workspace_id: "ws-1",
        name: "WORK",
        description: "Professional software development and client tasks",
        icon: "briefcase",
        color: "#3b82f6",
        sort_order: 0,
        created_at: "2026-09-01T08:00:00.000Z",
        updated_at: "2026-09-20T10:00:00.000Z",
        subcategories: [
          {
            id: "sub-1",
            category_id: "cat-1",
            name: "Web Development",
            description: "Frontend & backend development tasks",
            sort_order: 0,
            created_at: "2026-09-01T08:00:00.000Z",
            updated_at: "2026-09-20T10:00:00.000Z",
            tasks: [
              {
                id: "task-1",
                subcategory_id: "sub-1",
                parent_task_id: null,
                title: "Build Homepage",
                description: "Design and implement modern responsive homepage",
                notes: "Ensure mobile layout is verified on iOS and Android before release.",
                priority: "high",
                status: "in_progress",
                due_date: "2026-09-28T18:00:00.000Z",
                start_date: "2026-09-20T09:00:00.000Z",
                estimated_minutes: 240,
                actual_minutes: 120,
                completed_at: null,
                sort_order: 0,
                created_at: "2026-09-01T08:00:00.000Z",
                updated_at: "2026-09-20T10:00:00.000Z",
                subtasks: [
                  {
                    id: "task-1-sub-1",
                    subcategory_id: "sub-1",
                    parent_task_id: "task-1",
                    title: "Design layout wireframes",
                    description: null,
                    notes: null,
                    priority: "high",
                    status: "completed",
                    due_date: null,
                    start_date: null,
                    estimated_minutes: 60,
                    actual_minutes: 50,
                    completed_at: "2026-09-21T14:30:00.000Z",
                    sort_order: 0,
                    created_at: "2026-09-01T08:00:00.000Z",
                    updated_at: "2026-09-21T14:30:00.000Z",
                  },
                  {
                    id: "task-1-sub-2",
                    subcategory_id: "sub-1",
                    parent_task_id: "task-1",
                    title: "Build UI components",
                    description: null,
                    notes: null,
                    priority: "high",
                    status: "in_progress",
                    due_date: null,
                    start_date: null,
                    estimated_minutes: 120,
                    actual_minutes: 70,
                    completed_at: null,
                    sort_order: 1,
                    created_at: "2026-09-01T08:00:00.000Z",
                    updated_at: "2026-09-22T11:00:00.000Z",
                  },
                  {
                    id: "task-1-sub-3",
                    subcategory_id: "sub-1",
                    parent_task_id: "task-1",
                    title: "Test responsive layout",
                    description: null,
                    notes: null,
                    priority: "medium",
                    status: "not_started",
                    due_date: null,
                    start_date: null,
                    estimated_minutes: 60,
                    actual_minutes: null,
                    completed_at: null,
                    sort_order: 2,
                    created_at: "2026-09-01T08:00:00.000Z",
                    updated_at: "2026-09-01T08:00:00.000Z",
                  },
                ],
              },
              {
                id: "task-2",
                subcategory_id: "sub-1",
                parent_task_id: null,
                title: "Create REST API endpoints",
                description: "Setup database queries and endpoints for data fetching",
                notes: "Add authentication middleware to protect user workspace endpoints.",
                priority: "medium",
                status: "not_started",
                due_date: "2026-09-30T18:00:00.000Z",
                start_date: null,
                estimated_minutes: 180,
                actual_minutes: null,
                completed_at: null,
                sort_order: 1,
                created_at: "2026-09-01T08:00:00.000Z",
                updated_at: "2026-09-01T08:00:00.000Z",
                subtasks: [],
              },
            ],
          },
          {
            id: "sub-2",
            category_id: "cat-1",
            name: "Job Applications",
            description: "Applications and portfolio updates",
            sort_order: 1,
            created_at: "2026-09-01T08:00:00.000Z",
            updated_at: "2026-09-20T10:00:00.000Z",
            tasks: [
              {
                id: "task-3",
                subcategory_id: "sub-2",
                parent_task_id: null,
                title: "Update CV & Portfolio",
                description: "Add latest project experiences and achievements",
                notes: "Export in both PDF and DOCX formats.",
                priority: "high",
                status: "completed",
                due_date: "2026-09-18T18:00:00.000Z",
                start_date: null,
                estimated_minutes: 90,
                actual_minutes: 85,
                completed_at: "2026-09-18T17:00:00.000Z",
                sort_order: 0,
                created_at: "2026-09-01T08:00:00.000Z",
                updated_at: "2026-09-18T17:00:00.000Z",
                subtasks: [],
              },
              {
                id: "task-4",
                subcategory_id: "sub-2",
                parent_task_id: null,
                title: "Apply to target companies",
                description: "Submit applications for Senior Frontend / Fullstack roles",
                notes: null,
                priority: "urgent",
                status: "in_progress",
                due_date: "2026-09-29T18:00:00.000Z",
                start_date: null,
                estimated_minutes: 120,
                actual_minutes: null,
                completed_at: null,
                sort_order: 1,
                created_at: "2026-09-01T08:00:00.000Z",
                updated_at: "2026-09-20T10:00:00.000Z",
                subtasks: [],
              },
            ],
          },
        ],
      },
      {
        id: "cat-2",
        workspace_id: "ws-1",
        name: "PERSONAL",
        description: "Personal errands, finance, and wellness",
        icon: "user",
        color: "#10b981",
        sort_order: 1,
        created_at: "2026-09-01T08:00:00.000Z",
        updated_at: "2026-09-20T10:00:00.000Z",
        subcategories: [
          {
            id: "sub-3",
            category_id: "cat-2",
            name: "Finance & Planning",
            description: "Monthly budget and investment checks",
            sort_order: 0,
            created_at: "2026-09-01T08:00:00.000Z",
            updated_at: "2026-09-20T10:00:00.000Z",
            tasks: [
              {
                id: "task-5",
                subcategory_id: "sub-3",
                parent_task_id: null,
                title: "Review monthly subscriptions",
                description: "Audit unused SaaS and subscription services",
                notes: null,
                priority: "low",
                status: "completed",
                due_date: "2026-09-20T18:00:00.000Z",
                start_date: null,
                estimated_minutes: 30,
                actual_minutes: 25,
                completed_at: "2026-09-20T16:00:00.000Z",
                sort_order: 0,
                created_at: "2026-09-01T08:00:00.000Z",
                updated_at: "2026-09-20T16:00:00.000Z",
                subtasks: [],
              },
            ],
          },
        ],
      },
    ],
  },
];
